#!/bin/sh

IMAGE_ROOT=/Volumes/Spare/Flickr

case $1 in
  web|w)
    FLASK_APP=dejunk.py flask run
    ;;
  import|i)
    python import.py
    ;;
  check|c)
    python check.py
    ;;
  fixup|f)
    python fixup.py
    ;;
  dups|d)
    python dups.py $2
    ;;
  purge|p)
    python purge.py
    ;;
  make)
    ln -s $IMAGE_ROOT/thumbs/ static/
    ln -s $IMAGE_ROOT/medium/ static/
    ln -s $IMAGE_ROOT/images/ static/
    ;;
  break)
    rm static/thumbs
    rm static/medium
    rm static/images
    ;;
  *)
    echo "Unknown command: $1"
    echo
    echo "web - run the site on http://localhost:5000"
    echo "import - import the new images from ${IMAGE_ROOT}/import"
    echo "check - report problems"
    echo "fixup - fix problems"
    echo "purge - remove all junk images"
    echo "make - make the links to where the images are stored"
    echo "break - remove the links to the images"
    exit 0
esac
